### PR TITLE
Update Apexchart to latest version

### PR DESCRIPTION
**Pull request by gabriele-mastrapasqua**
This pull request updates apexchart dependency and should fixes some issues old apexchart had, like irregular logaritmic graphs bugs on y-axis, etc. fixed on newer version of the library.

[vue3-apexcharts](https://github.com/apexcharts/vue3-apexcharts) uses an apexchart version from 1 year ago, so I needed to update the library this wrapper uses.

### CODE REVIEW

**Comment by CreativeWarlock** [comment]
Great! I'm looking forward to the merge! When will it come??

**Review by ytechcsl — APPROVED** [review]

**Comment by CreativeWarlock** [comment]
Great, nice to see activity here! Will the new version be available on npm.js soon, too?

**Comment by kenzo08** [comment]
I have a problem with xaxis label  in type datetime, it indicate  reapting month, can you merge please, may be here is solution this proble

**Review by FabianMontoya — APPROVED** [review]

**Comment by FabianMontoya** [comment]
Looks nice, I don't know why the PR isn't complete yet :-/

**Comment by Guziq** [comment]
Because this repo is abandoned.

**Comment by kenzo08** [comment]
> why? do you know alternative graph generator  for vue 3?

**Review by junedchhipa — APPROVED** [review]

**Pull request merged**
