### PR TITLE
added global variable

### PR DESCRIPTION
**Pull request by Sitronik**
Added global variable $apexcharts

To support projects that used this.$apexcharts.exec call and other methods in the module - [https://github.com/apexcharts/vue-apexcharts](https://github.com/apexcharts/vue-apexcharts)

### CODE REVIEW

**Review by junedchhipa — APPROVED** [review]

**Comment by Sitronik** [comment]
@junedchhipa Hello, publish please new version of vue3-apexcharts to npm. Thank you

**Comment by junedchhipa** [comment]
Sure, I will. I wanted to fix the typescript issue before that.
If you have any experience with TypeScript, do you know where should I put the [Typescript declaration](https://github.com/apexcharts/vue3-apexcharts/blob/main/typings/vue-apexcharts.d.ts)?

**Comment by Sitronik** [comment]
Good, try adding "typings": "./typings/vue-apexcharts.d.ts" to package.json

**Comment by junedchhipa** [comment]
Thanks.
Unfortunately, I had to remove the global import as it added 400 kb to the final build

Screenshot 2021-01-12 at 9 56 37 PM

**Comment by junedchhipa** [comment]
After removing ApexCharts import.

Screenshot 2021-01-12 at 9 58 28 PM

**Comment by Sitronik** [comment]
Ok

**Pull request merged**
